version: '3.3'
services:
  post_db:
    env_file:
      - .env
    image: mongo:${MONGO_VER}
    volumes:
      - post_db:/data/db
    networks:
      - back_net
  ui:
    env_file:
      - .env
    build: ./ui
    image: ${USERNAME}/ui:${UI_VER}
    ports:
      - ${EXTERNAL_PORT}:${INTERNAL_PORT}/tcp
    networks:
      - front_net
  post:
    env_file:
      - .env
    build: ./post-py
    image: ${USERNAME}/post:${POST_VER}
    networks:
      - back_net
      - front_net
  comment:
    env_file:
      - .env
    build: ./comment
    image: ${USERNAME}/comment:${COMMENT_VER}
    networks:
      - back_net
      - front_net

volumes:
  post_db:

networks:
  back_net:
  front_net:
